
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet; 
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chandrimaghosh/Nishant Shetty
 */
public class HomePage extends javax.swing.JFrame {
     ArrayList<Patient> patients=new ArrayList<>();
     Doctor doc=new Doctor();
     
    /**
     * Creates new form HomePage
     */
    public HomePage(String docname) {
        initComponents();
        patientTable.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
                
            },
            new String [] {
                "PatientID","PatientName","PatientEmail"}
        ));
       
         this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        
        Doctor docglobal=new Doctor();
        try{
        PreparedStatement doc_Details =login.con.prepareStatement
            
        ("select Dname,Did,Demail from Doctor where Duname=?;");
            	  doc_Details.setString(1, docname);
            	  ResultSet rs = doc_Details.executeQuery();
            	   while(rs.next()){
                       System.out.println(rs.getString(1));
                       doc.setDoctorname(rs.getString(1));
                       doc.setDocID(rs.getInt(2));
                       doc.setDoctoremail(rs.getString(3));
            		   
                      }  
                   jLabel6.setText(Integer.toString(doc.getDocID()));
                   jLabel7.setText(doc.getDoctorname());
                   jLabel8.setText(doc.getDoctoremail());
                    
           
            
                           
              
            PreparedStatement p_Details =login.con.prepareStatement
                ("select Pname,Pid,Pemail from Patient where Pconsults=?;");
            	  p_Details.setInt(1, doc.getDocID());
                    ResultSet r = p_Details.executeQuery();
                 
              
            	  
                  while(r.next()){
                      Patient pat=new Patient();
                       System.out.println(r.getString(1));
                       pat.setPatient_name(r.getString(1));
                       pat.setPid(r.getInt(2));
                       pat.setPatient_email(r.getString(3));
                       patients.add(pat);
           		    }
                 Iterator<Patient> pt = patients.iterator();
                 Iterator<Patient> pt2 = patients.iterator(); 
                  
                    while(pt2.hasNext()) {
                  
                    Patient pat=new Patient();
                  
                    pat=pt2.next();
            
                    System.out.println(pat.getPid());}
                   jLabel6.setText(Integer.toString(doc.getDocID()));
                   jLabel7.setText(doc.getDoctorname());
                   jLabel8.setText(doc.getDoctoremail());
                   populatetable();
                   int rowCount=patientTable.getRowCount();
       
                   DefaultTableModel dtm= (DefaultTableModel)patientTable.getModel();
                        for(int i=rowCount-1;i>0;i--){
                        dtm.removeRow(i);
                            }
        
        while(pt.hasNext()) {
           Patient pat=new Patient();
           pat=pt.next();
          
            Object row[] = new Object[3];
            row[0]=pat.getPid();
            row[1]=pat.getPatient_name();
            row[2]=pat.getPatient_email();
         
         dtm.addRow(row);
        }
               }
          catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }}
        
    public void populatetable(){
        
        
       
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        ViewOrder = new javax.swing.JButton();
        ViewProducts = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Doctor Id:");

        jLabel3.setText("Name:");

        jLabel4.setText("Email:");

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(patientTable);

        jLabel5.setText("Patient");

        ViewOrder.setText("View Order");
        ViewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewOrderActionPerformed(evt);
            }
        });

        ViewProducts.setText("View Product Availibility");
        ViewProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewProductsActionPerformed(evt);
            }
        });

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        jLabel8.setText("jLabel8");

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewProducts)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ViewOrder)))
                .addGap(103, 103, 103))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ViewProducts)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(ViewOrder))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jLabel6.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewProductsActionPerformed
      
        
        PlaceOrderJFrame pojf=new PlaceOrderJFrame(doc.getDocID(),"Doctor");
        pojf.setVisible(true);
       
    }//GEN-LAST:event_ViewProductsActionPerformed

    private void ViewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewOrderActionPerformed
    DoctorOrderManagerJframe view_cancel_order=new DoctorOrderManagerJframe(doc.getDocID(),"Doctor");
    view_cancel_order.setVisible(true);
    }//GEN-LAST:event_ViewOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.setVisible(false);
         try {
             login.con.close();
         } catch (SQLException ex) {
             Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewOrder;
    private javax.swing.JButton ViewProducts;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable patientTable;
    // End of variables declaration//GEN-END:variables
}
